# Generated by Django 6.0 on 2026-01-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
